from pydantic import BaseModel, Field
from typing import Optional, List

class ListingModel(BaseModel):
    listing_id: str
    property_id: str
    list_price_max: float
    list_price_min: float
    beds_max: int
    beds_min: int
    baths_max: float
    baths_min: float
    sqft_max: int
    sqft_min: int
    address: str = Field(alias="Address")
    postal_code: str = Field(alias="Postal Code")
    city: str = Field(alias="City")
    state: str = Field(alias="State")
    cats: Optional[bool] = Field(None, alias="Cats")
    dogs: Optional[bool] = Field(None, alias="Dogs")
    photos: List[str] = Field(default_factory=list, alias="Photos")
    details: str = Field(default="generated by ai in the pipeline", alias="Details")

    def from_dict(prop: dict):
        if prop["list_price_max"] is None or prop["list_price_min"] is None:
            print(prop)
        return ListingModel(
            listing_id=prop["listing_id"],
            property_id=prop["property_id"],
            list_price_max=prop["list_price_max"],
            list_price_min=prop["list_price_min"],
            beds_max=prop["description"]["beds_max"],
            beds_min=prop["description"]["beds_min"],
            baths_max=prop["description"]["baths_max"],
            baths_min=prop["description"]["baths_min"],
            sqft_max = prop["description"]["sqft_max"],
            sqft_min = prop["description"]["sqft_min"],
            address=prop["location"]["address"]["line"],
            postal_code=prop["location"]["address"]["postal_code"],
            city=prop["location"]["address"]["city"],
            state=prop["location"]["address"]["state_code"],
            cats=prop["pet_policy"]["cats"] if prop.get("pet_policy") else False,
            dogs=prop["pet_policy"]["dogs"] if prop.get("pet_policy") else False,
            photos=[photo["href"] for photo in prop.get("photos", [])],
            details=prop["amenities_description"]
        )
    class Config:
        populate_by_name = True  # allows using both alias and field name

class UnitModel(BaseModel):
    listing_id: str
    property_id: str
    availability: str
    beds: int
    baths: float
    sqft: Optional[int] = None
    list_price: Optional[float] = None

    def from_dict(unit: dict, listing_id: str, property_id: str):
        return UnitModel(
            listing_id=listing_id,
            property_id=property_id,
            availability= unit["availability"]["date"] if unit.get("availability") else "None", #TODO: Parse into a date type and insert null if not avaialable
            beds=unit["description"]["beds"],
            baths=unit["description"]["baths"],
            sqft=unit["description"]["sqft"],
            list_price=unit["list_price"]
        )